name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 463
          test_id: 2145
          profile_id: 951
          browser: chrome
          headless: false
          environment: QA
