name: Sedstart Local macOS

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: macos-15

    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runlocal@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 612
          test_id: 4876
          profile_id: 1017
          browser: "webkit"
