name: Run SedStart Test

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: DasTapan09/no-code@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 270
          test_id: 1186
          profile_id: 330
          browser: chrome
          headless: false
          environment: Prod

